#ifndef __MYDEV_H__
#define __MYDEV_H__

#define MYDEV_IOCTL_MAGIC	254

#define MYDEV_IOCTL_INIT	_IO(MYDEV_IOCTL_MAGIC, 0)
#define MYDEV_IOCTL_DEINIT	_IO(MYDEV_IOCTL_MAGIC, 1)
#define MYDEV_IOCTL_READ	_IO(MYDEV_IOCTL_MAGIC, 2)
#define MYDEV_IOCTL_WRITE	_IO(MYDEV_IOCTL_MAGIC, 3)
#define MYDEV_IOCTL_RDWR	_IO(MYDEV_IOCTL_MAGIC, 4)

#define MYDEV_IOCTL_MAX_NR	5

#endif /*__MYDEV_H__*/